### ISSUE TITLE
Can't resolve com.kenai.jffi.Type

### ISSUE THREAD

**Issue by cmosier** [jnr/jnr-ffi#118]
I am trying the example from the README.md:
```java
package com.powerdata.openpa.tools.matrix;

import jnr.ffi.LibraryLoader;
import jnr.ffi.annotations.IgnoreError;
import jnr.ffi.provider.FFIProvider;

public class JnrHelloWorld
{
	public interface GetPid
	{
		@IgnoreError
		long getpid();
	}
	public static void main(String[] args)
	{
		LibraryLoader<GetPid> loader = FFIProvider.getSystemProvider().createLibraryLoader(GetPid.class);
		GetPid gp = loader.load("c");
		System.out.println(gp.getpid());
		
	}
}
```

And I can not resolve the com.kenai.jffi.Type class:

  Exception in thread "main" java.lang.UnsatisfiedLinkError: could not load FFI provider 
  jnr.ffi.provider.jffi.Provider
  	at jnr.ffi.provider.InvalidProvider$1.loadLibrary(InvalidProvider.java:48)
  	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:325)
  	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:304)
  	at com.powerdata.openpa.tools.matrix.JnrHelloWorld.main(JnrHelloWorld.java:17)
  Caused by: java.lang.NoClassDefFoundError: com/kenai/jffi/Type
  	at jnr.ffi.provider.jffi.NativeRuntime.jafflType(NativeRuntime.java:202)
  	at jnr.ffi.provider.jffi.NativeRuntime.buildTypeMap(NativeRuntime.java:85)
  	at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:66)
  	at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
  	at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:62)
  	at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:58)
  	at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
  	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  	at 
  sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
	at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
	at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
	at com.powerdata.openpa.tools.matrix.JnrHelloWorld.main(JnrHelloWorld.java:16)
Caused by: java.lang.ClassNotFoundException: com.kenai.jffi.Type
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more

I'm only trying at this point to get started with the basics.  Any pointers would be very helpful.  Thanks!

**Comment by cmosier** [comment]
I am using the 2.1.5 release tag

**Comment by cmosier** [comment]
Resolved, I didn't have dependencies set up correctly.

**Comment by tjanson** [comment]
I know it’s been a while, but do you remember what exactly the issue with the dependencies was @cmosier? (I have the same problem. Using Ant/Ivy, with `com.github.jnr#jnr-ffi` somewhere deep down in the dependency tree …)

**Comment by cmosier** [comment]
The dependency is located in [jffi](https://github.com/jnr/jffi).  Once I built the jar and provided it on the classpath correctly, it resolved com.kenai.jffi.Type

The JAR files and their versions that I use to resolve everything (well...that I am using anyway):

asm-6.0.jar
jffi-1.2.16.jar
jffi-1.2.16-complete.jar
jffi-1.2.16-native.jar
jnr-constants-0.9.9.jar
jnr-ffi-2.1.7.jar
jnr-posix-3.0.44.jar
jnr-x86asm-1.0.2.jar

To be honest, I'm not sure about the differences between jffi-1.2.16.jar and jffi-1.2.16-complete.jar, they may be redundant.

**Comment by tjanson** [comment]
Thanks for getting back so quickly, I appreciate it! Got me on the right track. I only had the `jffi-VERSION-native.jar`, also adding the `jffi-VERSION.jar` worked. Ivy only retrieved one or the other.

For anyone else possibly running into this **with Ant/Ivy**, here’s how I got Ivy to retrieve both.

-----

First off, adding an explicit dependency and disabling conflict resolution like so worked for me, **but I’m pretty sure this is both a bad idea and not generally a solution**.

```xml
        <dependency org="com.github.jnr" name="jffi" rev="1.2.17"/>
        <conflict manager="all"/>
```

-----

The second solution looks a lot cleaner: 

In `ivy.xml`, specify the artifact type like this, which for reasons I don’t understand results in Ivy getting both the `-native` and regular jar:

```xml
        <dependency org="com.github.jnr" name="jffi" rev="1.2.13">
            <artifact name="jffi" type="jar"/>
        </dependency>
```

To accommodate both files being downloaded, I also had to modify the Ivy retrieve pattern in the Ant `build.xml` like this:

```xml
        <ivy:retrieve pattern="lib/[originalname].[ext]"/>
```

-----

See also: [somewhat related SO post](https://stackoverflow.com/a/24946226), [Ivy artifact](https://ant.apache.org/ivy/history/latest-milestone/ivyfile/dependency-artifact.html), [Ivy pattern](https://ant.apache.org/ivy/history/latest-milestone/concept.html#__a_id_patterns_a_patterns), in particular:

> Indeed, when a module has no Ivy file, **it is assumed that it publishes exactly one artifact having the same name as the module itself. But when this module publishes more artifacts**, or simply does not respect the name rule, and if you cannot deliver an Ivy file for it (because you do not control the repository, for instance - think about Maven ibiblio repository, to give no name), **then this feature lets you specify the artifact names you want to get**.

**Comment by jollyjoker992** [comment]
@cmosier @tjanson 
Sorry because I need some helps from you guys. I am modifying some code in both [jnr-ffi]("https://github.com/jnr/jnr-ffi") and [jffi]("https://github.com/jnr/jffi") and rebuild the jar file for my project library but when I run the code, it always happens the bug 

> java.lang.NoClassDefFoundError: jnr/ffi/Platform$OS

So, do you guys have any idea to solve it? Thanks

**Comment by tjanson** [comment]
@jollyjoker992 For the error I had it was necessary to have both `jffi-VERSION.jar` and `jffi-VERSION-native.jar`, as I said. I don’t know anything else about this project. I’m guessing it’s a similar dependency resolution issue, but I have no idea.
