### ISSUE TITLE
java.lang.VerifyError when converting @size_t to int

### ISSUE THREAD

**Issue by zhanhb** [jnr/jnr-ffi#150]
```java
@size_t int strlen(byte[] str); // this failed on x64
```
https://github.com/zhanhb/jnr-ffi/commit/97022703796389665999a0537f838abca18b2280
https://travis-ci.org/zhanhb/jnr-ffi/builds/294321072

**Comment by zhanhb** [comment]
```
Running jnr.ffi.LibCTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.012 sec <<< FAILURE! - in jnr.ffi.LibCTest
testStrlen(jnr.ffi.LibCTest)  Time elapsed: 0.009 sec  <<< ERROR!
java.lang.RuntimeException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    jnr/ffi/LibCTest$Libc$jnr$ffi$66.strlen([B)I @32: ireturn
  Reason:
    Type long_2nd (current frame, stack[1]) is not assignable to integer
  Current Frame:
    bci: @32
    flags: { }
    locals: { 'jnr/ffi/LibCTest$Libc$jnr$ffi$66', '[B', integer }
    stack: { long, long_2nd }
  Bytecode:
    0x0000000: b200 0c2a b400 102a b400 142b 033d c600
    0x0000010: 0a09 8402 01a7 0004 091c 9a00 07b6 001a
    0x0000020: ac1c 2bb8 0020 4e2b 2d2a b400 24b6 0028
    0x0000030: a7ff f0                                
  Stackmap Table:
    full_frame(@24,{Object[#2],Object[#42],Integer},{Object[#22],Object[#44],Long})
    full_frame(@25,{Object[#2],Object[#42],Integer},{Object[#22],Object[#44],Long,Long})
    same_locals_1_stack_item_frame(@32,Long)
    full_frame(@33,{Object[#2],Object[#42],Integer},{Object[#22],Object[#44],Long,Long})
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:236)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:89)
	at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:44)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:325)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:304)
	at jnr.ffi.LibCTest.setupClass(LibCTest.java:18)
```

**Comment by headius** [comment]
Hello again! I did not notice this issue until now...we are a bit understaffed maintaining these libraries.

I notice you started some fixes at https://github.com/zhanhb/jnr-ffi before you made your new version at https://github.com/zhanhb/jnc-build. Could we perhaps work together on jnr-ffi? We'd be very grateful for your help!

**Comment by zhanhb** [comment]
JVM may crash when reload the lib. For my website need reload very often. So I wrote a my own version.
