### ISSUE TITLE
jffi9396993929588479283.so: /lib64/libc.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by kingluo** [jnr/jnr-ffi#313]
The error message is very weird:

```
...
Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
        at jnr.ffi.provider.InvalidRuntime.newLoadError(InvalidRuntime.java:102)
        at jnr.ffi.provider.InvalidRuntime.getMemoryManager(InvalidRuntime.java:53)
        at jnr.ffi.Pointer.wrap(Pointer.java:48)
        at demo.echo.PollThread.run(App.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.UnsatisfiedLinkError: could not get native definition for type `POINTER`, original error message follows: java.lang.UnsatisfiedLinkError: Unable to
 execute or load jffi binary stub from `/home/`. Set `TMPDIR` or Java property `java.io.tmpdir` to a read/write path that is not mounted "noexec".
.../jffi9396993929588479283.so: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by .../jffi9396993929588479
283.so)
        at com.kenai.jffi.internal.StubLoader.tempLoadError(StubLoader.java:555)
...
```

It reports `noexec` problem, but the `/home` is not mounted with `noexec`, is it symbol issue?
I found only `memfd_create` C symbol comes from `GLIBC_2.27'.

Please help, thanks.

**Comment by Sobakaa** [comment]
Faced the same issue recently. Still investigating, not sure yet if it's tied to a java update or centos update on our side, as it used to work about a month ago.

**Comment by Sobakaa** [comment]
Not an issue on our end, it seems. Once i downgraded to jnr 2.1.12 the problem disappeared. Sadly will have to exclude this library from auto-updates for the time being.

**Comment by DManstrator** [comment]
I am also facing this exact issue.

```
Failed to execute goal io.fabric8:docker-maven-plugin:0.41.0:build (default) on project my-project: Execution default of goal io.fabric8:docker-maven-plugin:0.41.0:build failed: An API incompatibility was encountered while executing io.fabric8:docker-maven-plugin:0.41.0:build: java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
[...]
Caused by: java.lang.UnsatisfiedLinkError: could not get native definition for type `POINTER`, original error message follows: java.lang.UnsatisfiedLinkError: Unable to execute or load jffi binary stub from `/tmp/foobar`. Set `TMPDIR` or Java property `java.io.tmpdir` to a read/write path that is not mounted "noexec".
/appl/bamboo-agent/xml-data/build-dir/[...]/jffi16914516266569452708.so: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /appl/bamboo-agent/xml-data/build-dir/[...]/jffi16914516266569452708.so)
```

The [latest `docker-maven-plugin` update (v0.41.0)](https://github.com/fabric8io/docker-maven-plugin/releases/tag/v0.41.0) updated `JNR UnixSocket` to v0.38.19. This however updated [JNR-FFI from 2.1.11 to 2.1.13](https://github.com/jnr/jnr-unixsocket/compare/jnr-unixsocket-0.38.17...jnr-unixsocket-0.38.19#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L59-L64).

Since then my bamboo builds are failing. When going back to `docker-maven-plugin` v0.40.3, the builds are running through again.

**Comment by RainerGanss** [comment]
We have the same error which is prevent us to upgrade to the newest version.

**Comment by headius** [comment]
Looking into this now. Anyone have any idea what version this started at?

Over the past year we've moved to using GHA to do builds of all the Linux-based jffi binaries. When building for x86_64, I believe we just build directly on GHA, so it's going to be a very recent version of Ubuntu/Debian-ish Linux. If we need to be mindful of the glibc version, that will require some finesse.

**Comment by headius** [comment]
> This however updated [JNR-FFI from 2.1.11 to 2.1.13](https://github.com/jnr/jnr-unixsocket/compare/jnr-unixsocket-0.38.17...jnr-unixsocket-0.38.19#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L59-L64).

@DManstrator So that narrows it down, thank you.

**Comment by headius** [comment]
FWIW this is really a jffi issue so I'm going to move it there.
