### ISSUE TITLE
"Expecting to find integer on stack" when using @Delegate

### ISSUE THREAD

**Issue by jahewson** [jnr/jnr-ffi#6]
I'm getting a runtime exception when trying to use a delegate.

```
Exception in thread "main" java.lang.RuntimeException: java.lang.VerifyError: (class: foo/External$Lib$jnr$ffi$2, method: Process signature: (Lfoo/External$FailureCallback;J[B)Z) Expecting to find integer on stack
    at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:201)
    at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:59)
    at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:43)
    at jnr.ffi.LibraryLoader.load(LibraryLoader.java:228)
    at jnr.ffi.LibraryLoader.load(LibraryLoader.java:201)
```

The code I'm using is simply:

``` java
 protected interface Lib  {
    boolean Process(byte[] data, Callback callback);
 }

 public static interface Callback {
    @Delegate public void call();
 }
```

The problem seems to be something to do with the parameter types because changing `data` from `byte[]` to `long` works fine.

**Comment by headius** [comment]
Still a problem? If so, can you express this in terms of a PR with failing a failing test case?

**Comment by lionel1704** [comment]
Hey @jahewson I'm trying to do something similar. But I'd like my call() function to have an argument. Eg:
```
public static interface Callback {
    @Delegate public void call(FfiResult result);
 }
```
Any idea how I can proceed ?
