### ISSUE TITLE
can not create provider

### ISSUE THREAD

**Issue by kingchenchina** [jnr/jnr-ffi#74]
with code Class.forName("jnr.ffi.provider.jffi.Provider").newInstance(); it throws exception:
Exception in thread "main" java.lang.ExceptionInInitializerError
	at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:49)
	at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at java.lang.Class.newInstance0(Class.java:372)
	at java.lang.Class.newInstance(Class.java:325)

the NativeRuntime has a private class constructor, and it cause the exception

**Comment by headius** [comment]
Why do you need to do this?
